# ov50 Linux/OSX build - courtesy to https://github.com/seandepagnier
language: cpp

matrix:
  include:
    - env:
        - OCPN_TARGET=xenial
      dist: xenial
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=trusty
      dist: trusty
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=osx
      os: osx
      compiler: clang
      script:
        - bash ./ci/travis-build-osx.sh

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi
  - ls -l;

notifications:
  email: false
git:
  depth: 10
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
deploy:
- provider: releases
  api_key:
    secure: "PaERmLIkBuxuH0dU3wBkTlxJ1T/YdNKn1aV5b/iYu9W7RP8fIwoMJ7xwPuAa+6Gl7PcumTTXEk4K7F4aSpa1j1Q2FzUH/V+EuicBAdijs3w6aBTxDt2YEIEhGthzP9bwPBMEiJaroomcXs4xaK3vKeCuu+P2qDwYbTwtJjzxWSRDhAHm4aJmY1G51gV3aAZzWDVApC9Bul5nwtmzmgwRKlQGLL3f/OOb8oR4PFKQrwT7y3kDLS+XCxssSKcgAJYdmQlJBwHxlluobxJRbk+3zVEdr61PS3F0yBBojI1UFniM/zqAni/BidN90WtSq3Pvwhz+FeTdXztyKVzPiUAP4HqntK7/Mosglkgdn6/myDQuoX3r4jEP/kNGFTsg5s2uAyCpLruM7uGWIZWpDsWMt1bmD8IklEaBf9EQV67QCN7FVQAYdaIsPB0fbCyqsEL5ZZMpV4z5kPqGhPHxoxeNbtTfJK976kytqp2UkR3F5rV91+y9osBOx+LZI1EwlTSOdB4clOCr9fbQ0B+yVPjPw5WPqhB4TqEziWVRw/UX2Umdwqs73isZ4qrPjq9j2oKMSecE4XLi7ec4dFpR3An+KGa1KOqHNOfKBgR+L761nqLr3GUdM1nRwZJsnWIkiGOGFM47mK2D0UpCYrWubPRbMR2Jl3b8K/beeUUZNeqt1vk="
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/build/*.{deb,rpm,dmg,txz,pkg,pkg.tar.xz}"
  skip_cleanup: true
  on:
    repo: rgleason/tactics_pi
    tags: true
    all_branches: true
    
