# ov50 Linux/OSX build - courtesy to https://github.com/seandepagnier
language: cpp

matrix:
  include:
    - env:
        - OCPN_TARGET=xenial
      dist: xenial
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=trusty
      dist: trusty
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=osx
      os: osx
      compiler: clang
      script:
        - bash ./ci/travis-build-osx.sh

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi
  - ls -l;

notifications:
  email: false
git:
  depth: 10
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
deploy:
- provider: releases
  api_key:
    secure: "OwPza7d42z0s7TnD3V1/0gpEGqaEsW7/Y3IAm+HTNLhTlPScBMgeYNmrl4v1db0eKuAEVR85+rc6JS9wwRbtqlNHp8tkimvvsyoMeVIXiP357JmnmDtAcDiuxNm6jrnHuQbsmdD6J6oIe932/FS/flwWfh5FbcCl3zNra4VJJBkyleqFEc7ZArYDcfE1oxxpzfyHtuImF15qLEv1aMmfTLP77eBCI7jLUo1nK6P40gyja51oyderRZtgRPWoOc2ukHPQoziriPg6dIKRiFWHTdow9dCsVckoS+atY3y5Oic7GhIS9Pa/S3Rv1yjPm2o9RhmxBfP1EkR0RsmIV9wqT1GSvMR9EdLCgy43z9f5uxhVIsbBLfBdFcOP5GzY4kd9xovkgHsL4fKrderJvPYp/FjLKGRN9ZtK5fGvtLjSixzvVlJ74i1lfcK+QuXTv83WUx7aAxNTsuSJi0JrAu7DrNyoVk+ScORcsnF20vxZN53EsYiaw9Zakf8XAlqo4OeK7KuQJ8/K+wm85W66yXKg9DZZ+XsYefBZ29j40dT4MDn8N9YWbCCf7v4zwbGFd2anqSEum90XPRlGwqGMlPKpEMuRyWv5YWu69nSTyB9Vm1JI5pfth+wADsmoweANFiJ5YNKbrsrqROHpdrAlGXs5uv/+yKMiFNyygxad074yAiM="
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/build/*.{deb,rpm,dmg,txz,pkg,pkg.tar.xz}"
  skip_cleanup: true
  on:
    repo: rgleason/tactics_pi
    tags: true
    all_branches: true
    
